# proxy settings
proxy:
  http_proxy: null
  https_proxy: null

# comfyui settings
comfyui:
  comfyui_address: "127.0.0.1:8188"
  execution_timeout: 300

# embedding api for retrieval
embedding:
  base_url: null
  api_key: null
  model_name: "text-embedding-3-large"

# completion api for agent
completion:
  base_url: null
  api_key: null
  model_name: "chatgpt-4o-latest"
  hyper_parameter:
    temperature: 0.0
    top_p: 1.0

# vision api for evaluation
vision:
  base_url: null
  api_key: null
  model_name: "chatgpt-4o-latest"
  hyper_parameter:
    temperature: 0.0
    top_p: 1.0
